# Generated by Django 3.0.3 on 2020-02-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_auto_20200224_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductlist',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderProductList', to='shopApp.Order'),
        ),
    ]
